### ISSUE TITLE
Unable to use inline yaml when running in docker

### ISSUE THREAD

**Issue by lassegaardsholt** [BESTSELLER/harpocrates#20]
When using yaml as inline, it fails with:
```
/docker-entrypoint.sh: line 11: /format: env
output: "/secrets"
prefix: PREFIX_
secrets:
  - secret/data/secret/dev
  - secret/data/foo:
      prefix: TEST_
      keys:
       - APIKEY
       - BAR:
           prefix: "BOTTOM_"
       - TOPSECRET:
           saveToFile: true: No such file or directory
```

InitContainer looks like:
```yaml
initContainers:
      - image: harbor.bestsellerit.com/library/harpocrates:0.2.48
        args:
        - 'format: env
output: "/secrets"
prefix: PREFIX_
secrets:
  - secret/data/secret/dev
  - secret/data/foo:
      prefix: TEST_
      keys:
       - APIKEY
       - BAR:
           prefix: "BOTTOM_"
       - TOPSECRET:
           saveToFile: true'
```
