### ISSUE TITLE
Make it possible to make secrets optional

### ISSUE THREAD

**Issue by marklonquist** [BESTSELLER/harpocrates#272]
We like to standardize some of our secrets.yml file, eg always have an entry for the `service.json` secrets, but it is not always used. Can we make functionally to mark secrets as optional, so that secret-injector doesn't blow up? 😄 

Example:
```yaml
format: json
output: "/secrets"
# prefix: OLYMPUS_
secrets:
  - OLYMPUS/data/Namespaces/$K8S_CLUSTER_CLUSTER_NAMESPACE/Shared/$K8S_CLUSTER_OLYMPUS_ENVIRONMENT/misc:
      format: json
      filename: misc.json
  - OLYMPUS/data/Namespaces/$K8S_CLUSTER_CLUSTER_NAMESPACE/Services/$APP_NAME/$K8S_CLUSTER_OLYMPUS_ENVIRONMENT/service:
      format: json
      optional: true
      filename: service.json
```
