### ISSUE TITLE
[orb] unable to use "prefix" together with vault path

### ISSUE THREAD

**Issue by brondum** [BESTSELLER/harpocrates#62]
When using the CircleCI Orb it is not possible to use both `vault-path` and `prefix`. It simply does not use the `prefix` part. 

Example:
```yaml
- secret-injector/dump-secrets:
          vault-path: "somepath"
          prefix: TF_VAR_
```

Command:
```sh
  /harpocrates \
    --format "env" \
    --output "/tmp" \
    --secret "somepath"
fi
```
